### application.properties  ####
# Load Env File
spring.config.import=optional:file:.env[.properties]

# ---- App ----
spring.application.name=${SB_ENV_APP_NAME}

# ---- Spring Security ----
spring.security.user.name=${SB_ENV_SPRING_SECURITY_USER_NAME}
spring.security.user.password=${SB_ENV_SPRING_SECURITY_USER_PASSWORD}
spring.security.user.roles=${SB_ENV_SPRING_SECURITY_USER_ROLES}

# --- Spring Security -- To Disable the default Login Page..
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# ---- Datasource ----
spring.datasource.url=${SB_ENV_DB_URL}
spring.datasource.username=${SB_ENV_DB_USERNAME}
spring.datasource.password=${SB_ENV_DB_PASSWORD}
spring.datasource.driver-class-name=${SB_ENV_DB_DRIVER}

# ---- JPA / Hibernate ----
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ---- Server ----
server.port=${SB_ENV_SERVER_PORT}
spring.output.ansi.enabled=ALWAYS

# --- Logging ---
logging.level.org.springframework.boot.context.config=INFO
logging.level.com.zaxxer.hikari=DEBUG
logging.level.org.postgresql=DEBUG

