# application.properties (for modules\billing - resources\application.properties)

# ---- App ----
spring.application.name=Billing
server.port=8082

# disable default login
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# ---- DataSource (PostgreSQL @ Render) ----
spring.datasource.url=jdbc:postgresql://dpg-d3eqkjili9vc73dl41ug-a.frankfurt-postgres.render.com:5432/desisoft?sslmode=require
spring.datasource.username=numan
spring.datasource.password=mAV2Qo7pcgXeIakeukr6Vzj9C8tHkyp5
spring.datasource.driver-class-name=org.postgresql.Driver

# ---- JPA / Hibernate ----
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# ---- HikariCP ----
spring.datasource.hikari.pool-name=ApptHikariPool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.connection-timeout=30000

# (Optional) If you are not using Spring Batch:
# spring.batch.jdbc.initialize-schema=never
# spring.batch.job.enabled=false
